version: '3.8'

services: 
  flask-api: 
    build: . 
    container_name: sales-backend-api
    ports: 
      - "5001:5000"
    restart: always
    environment: 
      - FLASK_ENV=development
    command: gunicorn -w 4 -b 0.0.0.0:5000 run:app